name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Show system info
      run: uname -a && lsb_release -a
    - name: Print Greeting
      run: echo "Hello World"
    - name: Print GoodBye
      run: echo "Done - bye!"


        
        
    
